### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [ShanghaitechGeekPie/GeekPie2021Games#1]
*我已经确认该 Bug 仅仅影响用户体验，与安全无关。*

**Bug 描述**
上传不合法图片文件时，会一直停留在识别界面

**重现方法**
1. Go to 'https://g21g.geekpie.club/playground'
2. 上传一个不合法的jpg文件【例如把学校logo_red.svg改成logo_red.jpg上传】
3. 提示一直在识别
4. 返回到主页此div仍然存在

**预期的行为**
应该返回“您没能通过”或者错误

**截图**
![截图17981129429254](https://user-images.githubusercontent.com/29009234/111058321-cc3ff000-84c8-11eb-97fa-277f83605cbc.png)
![截图18720119878876](https://user-images.githubusercontent.com/29009234/111058327-d104a400-84c8-11eb-87b6-927100ae1206.png)

**Desktop (please complete the following information):**
 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by murez** [comment]
已修复，感谢提交
