### ISSUE TITLE
[Bug] Stage0中上传logo.svg或奇妙文件,使credit归零

### ISSUE THREAD

**Issue by hehelego** [ShanghaitechGeekPie/GeekPie2021Games#2]
*我已经确认该 Bug 仅仅影响用户体验，与安全无关。与安全相关的 Bug 或漏洞请直接发送邮件至 leaferx@outlook.com*

**Bug 描述**

处于stage0,在`playground`页面,提交页面上的`logo.svg`进行识别.  
console中没有输出识别结果和datalist的信息.  
刷新页面,发现自己的credit归零了.

**重现方法**
1. Go to `https://g21g.geekpie.club/playground`
2. Download [link](https://www.shanghaitech.edu.cn/_upload/tpl/00/20/32/template32/images/logo_red.svg)
3. upload the fetched svg file.

**预期的行为**
无返回结果,console无信息输出. credit归零

**截图**
如果需要，请在这里上传截图

**Desktop (please complete the following information):**
 - 操作系统： Arch Linux
 - 浏览器： Firefox
 - 浏览器版本（可选）： 86.0.1

> uname -a
`Linux sp-ideapad 5.11.6-arch1-1 #1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000 x86_64 GNU/Linux`

**其他你认为重要的信息**

**Comment by Ricemeal** [comment]
无法进入下一关也是一个关卡吗？

**Comment by Ricemeal** [comment]
昨天无法进入stage1、2；今天此时可以进入了
